const lessonData = {};

lessonData["01_The911Attacks.mp3"] = [{
    text: "The September 11 attacks happened in the United States in 2001. People call this day '9/11.' It was the biggest terrorist attack in history. A group called al-Qaeda hijacked four airplanes. This means they took control of the planes by force. They flew two of the planes into the Twin Towers in New York City. The towers were very tall office buildings. The fire from the crash made the buildings fall down. Another plane hit the Pentagon, which is a military building. The fourth plane crashed in a field because the passengers fought the terrorists. Almost 3,000 people died that day. It was a very sad day for the whole world. After this, traveling on airplanes became much harder. Security at airports became very strict. The United States started a war against terror groups in other countries. This event changed the world forever.",
    dict: { "attacks": "saldırılar", "happened": "oldu", "biggest": "en büyük", "terrorist": "terörist", "history": "tarih", "hijacked": "kaçırdı", "airplanes": "uçaklar", "control": "kontrol", "force": "güç/zor", "flew": "uçurdu", "tall": "uzun", "office": "ofis", "buildings": "binalar", "fire": "yangın", "crash": "çarpışma/kaza", "fall down": "yıkılmak/düşmek", "hit": "çarptı", "military": "askeri", "field": "tarla/alan", "passengers": "yolcular", "fought": "savaştı", "died": "öldü", "sad": "üzücü", "world": "dünya", "traveling": "seyahat etmek", "harder": "daha zor", "security": "güvenlik", "strict": "katı/sıkı", "started": "başladı", "war": "savaş", "against": "karşı", "changed": "değiştirdi", "forever": "sonsuza dek" },
    questions: [ {q:"Did the attacks happen in 2001?", a_en:"Yes", a_tr:"Evet"}, {q:"Did terrorists hijack four airplanes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they fly two planes into the Twin Towers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fourth plane hit a hospital?", a_en:"No", a_tr:"Hayır"}, {q:"Did the passengers fight the terrorists on the fourth plane?", a_en:"Yes", a_tr:"Evet"}, {q:"Did security at airports become stricter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did almost 3,000 people die?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_TheAirIndiaBombing.mp3"] = [{
    text: "The bombing of Air India Flight 182 was a terrible tragedy. It happened in 1985. A plane was flying from Canada to India. It had to stop in London. While the plane was over the Atlantic Ocean near Ireland, a bomb exploded. The bomb was hidden inside a suitcase. A group of extremists put it there. The explosion broke the plane, and it fell into the sea. Everyone on the plane died. There were 329 people on board. Most of them were from Canada. For a long time, this was the worst attack on a plane. The police investigated for many years. They checked the bags poorly and made mistakes. It is remembered as the worst mass murder in Canadian history.",
    dict: { "bombing": "bombalama", "terrible": "korkunç", "tragedy": "trajedi", "flying": "uçuyordu", "stop": "durmak", "over": "üzerinde", "ocean": "okyanus", "near": "yakınında", "exploded": "patladı", "hidden": "gizli", "inside": "içinde", "suitcase": "bavul", "extremists": "aşırılık yanlıları", "put": "koydu", "explosion": "patlama", "broke": "kırdı/parçaladı", "fell": "düştü", "sea": "deniz", "everyone": "herkes", "died": "öldü", "on board": "gemide", "most": "çoğu", "worst": "en kötü", "attack": "saldırı", "police": "polis", "investigated": "soruşturdu", "checked": "kontrol etti", "poorly": "kötü bir şekilde", "mistakes": "hatalar", "remembered": "hatırlanır", "mass": "toplu", "murder": "cinayet", "history": "tarih" },
    questions: [ {q:"Did the bombing happen in 1985?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the plane flying to India?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the bomb hidden inside a suitcase?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the plane fall into the sea?", a_en:"Yes", a_tr:"Evet"}, {q:"Did everyone on the plane die?", a_en:"Yes", a_tr:"Evet"}, {q:"Did airport security make mistakes?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it remembered as the worst mass murder in Canadian history?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_TheBaliBombings.mp3"] = [{
    text: "The Bali bombings happened in 2002 in Indonesia. Bali is a beautiful island where many people go for holidays. On a Saturday night, terrorists attacked a busy area called Kuta. Many tourists were there. The terrorists used three bombs. One bomb was in a backpack inside a bar. A very big bomb was in a car outside a club. The third bomb was near an American office. The explosions were very strong and caused a big fire. The attack killed 202 people. People from 21 different countries died. Many of the victims were young people from Australia. The attack destroyed many buildings and hurt the local people deeply. It took a long time for the island to recover. People built a memorial to remember those who died.",
    dict: { "beautiful": "güzel", "island": "ada", "holidays": "tatiller", "night": "gece", "attacked": "saldırdı", "busy": "kalabalık/meşgul", "area": "bölge", "tourists": "turistler", "used": "kullandı", "backpack": "sırt çantası", "outside": "dışında", "club": "kulüp", "near": "yakınında", "office": "ofis", "strong": "güçlü", "caused": "sebep oldu", "fire": "yangın", "killed": "öldürdü", "different": "farklı", "countries": "ülkeler", "victims": "kurbanlar", "young": "genç", "destroyed": "yok etti", "hurt": "incitti/yaraladı", "local": "yerel", "deeply": "derinden", "recover": "toparlanmak", "built": "inşa etti", "memorial": "anıt", "remember": "hatırlamak" },
    questions: [ {q:"Did the Bali bombings happen in 2002?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many people go to Bali for holidays?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the terrorists use three bombs?", a_en:"Yes", a_tr:"Evet"}, {q:"Was one bomb hidden in a car?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the explosions cause a big fire?", a_en:"Yes", a_tr:"Evet"}, {q:"Did 202 people die in the attack?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the island recover very quickly?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["04_TheBeslanSchoolSiege.mp3"] = [{
    text: "The Beslan school siege happened in Russia in 2004. It started on September 1st. In Russia, this is the first day of school. It is usually a happy celebration for children and parents. But a group of armed rebels attacked the school. They took more than 1,100 people as hostages. A hostage is a person who is held prisoner. Most of them were children. The rebels put everyone in the school gym. They gave them no food or water for three days. It was very hot and crowded. The rebels wanted the Russian army to leave their region. On the third day, there were explosions in the gym. The Russian soldiers attacked the school to save the people. In the fighting, 334 people died. More than half were children. It was a heartbreaking event that shocked the world.",
    dict: { "siege": "kuşatma", "started": "başladı", "first": "ilk", "usually": "genellikle", "happy": "mutlu", "celebration": "kutlama", "parents": "ebeveynler", "armed": "silahlı", "rebels": "isyancılar", "attacked": "saldırdı", "hostages": "rehineler", "prisoner": "mahkum", "gym": "spor salonu", "food": "yiyecek", "water": "su", "hot": "sıcak", "crowded": "kalabalık", "army": "ordu", "leave": "terk etmek", "region": "bölge", "third": "üçüncü", "explosions": "patlamalar", "soldiers": "askerler", "save": "kurtarmak", "fighting": "çatışma", "half": "yarım", "heartbreaking": "yürek parçalayıcı", "event": "olay", "shocked": "şok etti" },
    questions: [ {q:"Did the siege happen on the first day of school?", a_en:"Yes", a_tr:"Evet"}, {q:"Did rebels take more than 1,100 hostages?", a_en:"Yes", a_tr:"Evet"}, {q:"Were most of the hostages children?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they give them no food or water?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the hostages kept in the gym?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Russian soldiers attack to save them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did more than 300 people die?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_TheEntebbeHijacking.mp3"] = [{
    text: "The Entebbe hijacking happened in 1976. An Air France plane was flying from Israel to France. Four terrorists took control of the plane. Two were from Palestine and two were from Germany. They forced the pilot to fly to Uganda in Africa. The President of Uganda, Idi Amin, helped the terrorists. They kept the Jewish and Israeli passengers as hostages and let the others go. They said they would kill the hostages if their demands failed. Israel sent a special team of soldiers to save them. The soldiers flew very far in secret. They landed at the airport at night. They fought a short battle and rescued 102 people. The leader of the soldiers, Yonatan Netanyahu, was killed. It is famous because the rescue mission was very daring and successful.",
    dict: { "hijacking": "uçak kaçırma", "took": "aldı", "control": "kontrol", "forced": "zorladı", "pilot": "pilot", "fly": "uçmak", "helped": "yardım etti", "kept": "tuttu", "passengers": "yolcular", "let go": "gitmesine izin verdi", "others": "diğerleri", "kill": "öldürmek", "demands": "talepler", "failed": "başarısız oldu", "sent": "gönderdi", "special": "özel", "team": "takım", "soldiers": "askerler", "secret": "gizli", "landed": "indi", "airport": "havalimanı", "night": "gece", "fought": "savaştı", "short": "kısa", "battle": "savaş/çatışma", "rescued": "kurtardı", "leader": "lider", "famous": "ünlü", "mission": "görev", "daring": "cesur", "successful": "başarılı" },
    questions: [ {q:"Did terrorists take control of a plane?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they force the pilot to fly to Uganda?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the President of Uganda help the passengers?", a_en:"No", a_tr:"Hayır"}, {q:"Did they keep the Israeli passengers as hostages?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Israel send a special team of soldiers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the soldiers land at the airport at night?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the rescue mission successful?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_TheGarissaAttack.mp3"] = [{
    text: "The Garissa University attack happened in Kenya in 2015. It was early in the morning. Students were sleeping or studying for exams. Gunmen from a terrorist group entered the university. They killed the guards at the gate. Then they went into the classrooms and dorm rooms. They looked for Christian students to kill. They let some Muslim students go free. The attack lasted for a long time, about 15 hours. The students were very afraid. The police and army surrounded the buildings. Finally, the security forces killed the four gunmen. But it was too late for many. In the end, 148 people died. Most of them were young students with bright futures. It was a very sad day for Kenya. It showed that schools need better protection.",
    dict: { "early": "erken", "morning": "sabah", "sleeping": "uyuyorlardı", "studying": "çalışıyorlardı", "exams": "sınavlar", "gunmen": "silahlı adamlar", "entered": "girdi", "killed": "öldürdüler", "guards": "korumalar", "gate": "kapı", "classrooms": "sınıflar", "dorm": "yurt", "looked for": "aradılar", "free": "özgür", "lasted": "sürdü", "long": "uzun", "afraid": "korkmuş", "surrounded": "kuşattı", "forces": "güçler", "too late": "çok geç", "many": "birçoğu", "end": "son", "died": "öldüler", "bright": "parlak", "futures": "gelecekler", "sad": "üzücü", "showed": "gösterdi", "need": "ihtiyacı var", "better": "daha iyi", "protection": "koruma" },
    questions: [ {q:"Did the attack happen early in the morning?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the gunmen enter a university?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they kill the guards at the gate?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the attack last for only one hour?", a_en:"No", a_tr:"Hayır"}, {q:"Did the police and army surround the buildings?", a_en:"Yes", a_tr:"Evet"}, {q:"Did 148 people die?", a_en:"Yes", a_tr:"Evet"}, {q:"Do schools need better protection?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_TheGrandMosqueSeizure.mp3"] = [{
    text: "The Grand Mosque seizure happened in 1979 in Saudi Arabia. The Grand Mosque in Mecca is the most holy place for Muslim people. Violence is forbidden there. But a group of men with guns took over the mosque. Their leader said a new savior had come. They locked the doors and trapped thousands of people inside. The government was very shocked. They wanted to cause no damage to the holy building. The siege lasted for two weeks. The Saudi army had to fight hard to get the mosque back. They had help from French experts. Many people died during the fighting. The mosque was damaged but later repaired. After this event, the government of Saudi Arabia became much more strict about religion and rules in the country.",
    dict: { "seizure": "ele geçirme", "holy": "kutsal", "place": "yer", "violence": "şiddet", "forbidden": "yasak", "guns": "silahlar", "took over": "devraldı/ele geçirdi", "leader": "lider", "savior": "kurtarıcı", "come": "geldi", "locked": "kilitledi", "doors": "kapılar", "trapped": "tuzağa düşürdü", "thousands": "binlerce", "government": "hükümet", "shocked": "şok olmuş", "damage": "hasar", "lasted": "sürdü", "weeks": "haftalar", "fight": "savaşmak", "hard": "sert/zor", "back": "geri", "experts": "uzmanlar", "during": "sırasında", "repaired": "tamir edildi", "event": "olay", "strict": "katı/sıkı", "religion": "din", "rules": "kurallar" },
    questions: [ {q:"Is the Grand Mosque a holy place?", a_en:"Yes", a_tr:"Evet"}, {q:"Is violence forbidden in the mosque?", a_en:"Yes", a_tr:"Evet"}, {q:"Did men with guns take over the mosque?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they lock the doors?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the siege last for two weeks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Saudi army get help from French experts?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government become more strict after this?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_TheJonestownMassacre.mp3"] = [{
    text: "The Jonestown Massacre happened in 1978 in Guyana. It involved a group called the Peoples Temple. The leader was a man named Jim Jones. He told people to move to the jungle to build a perfect place to live. But life there was hard. Jones was a bad leader. He controlled everyone. A politician from the USA came to visit and check on the people. Jones ordered his men to kill the politician. Then, Jones told all his followers that they must die. He made a drink mixed with poison. He told parents to give it to their babies first. Then the adults drank it. In total, 918 people died. It was a terrible tragedy. It showed how dangerous cult leaders can be when they have too much power over people.",
    dict: { "massacre": "katliam", "involved": "içeriyordu", "called": "adlandırılan", "leader": "lider", "named": "adında", "told": "söyledi", "move": "taşınmak", "jungle": "orman", "build": "inşa etmek", "perfect": "mükemmel", "live": "yaşamak", "life": "hayat", "hard": "zor", "bad": "kötü", "controlled": "kontrol etti", "politician": "politikacı", "visit": "ziyaret etmek", "check": "kontrol etmek", "ordered": "emretti", "kill": "öldürmek", "followers": "takipçiler", "must": "zorunda", "die": "ölmek", "drink": "içecek", "mixed": "karışık", "poison": "zehir", "parents": "ebeveynler", "babies": "bebekler", "adults": "yetişkinler", "drank": "içti", "total": "toplam", "terrible": "korkunç", "dangerous": "tehlikeli", "cult": "tarikat", "power": "güç" },
    questions: [ {q:"Was Jim Jones the leader of the group?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they move to the jungle?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Jim Jones a bad leader?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he order his men to kill a politician?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he mix a drink with poison?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the adults drink the poison first?", a_en:"No", a_tr:"Hayır"}, {q:"Did 918 people die?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_TheLockerbieBombing.mp3"] = [{
    text: "The Lockerbie bombing happened in 1988. Pan Am Flight 103 was flying to New York. It was high in the sky over Scotland. Suddenly, a bomb exploded on the plane. The bomb was hidden inside a radio in a suitcase. The explosion broke the plane into pieces. It fell onto a small town called Lockerbie. All 259 people on the plane died. Large parts of the plane hit houses on the ground. This killed 11 more people in the town. In total, 270 people lost their lives. Investigators looked at the pieces of the plane for a long time. They found out that men from Libya planned the attack. It is the worst terrorist attack that ever happened in the United Kingdom. People in Lockerbie still remember the victims today.",
    dict: { "flying": "uçuyordu", "high": "yüksek", "sky": "gökyüzü", "over": "üzerinde", "suddenly": "aniden", "exploded": "patladı", "hidden": "gizli", "inside": "içinde", "radio": "radyo", "suitcase": "bavul", "explosion": "patlama", "broke": "kırdı/parçaladı", "pieces": "parçalar", "fell": "düştü", "onto": "üzerine", "small": "küçük", "town": "kasaba", "large": "büyük", "parts": "kısımlar/parçalar", "hit": "çarptı", "houses": "evler", "ground": "yer/zemin", "killed": "öldürdü", "lost": "kaybetti", "lives": "hayatlar", "investigators": "müfettişler", "looked at": "baktı/inceledi", "long time": "uzun zaman", "planned": "planladı", "worst": "en kötü", "ever": "şimdiye kadar", "still": "hala", "remember": "hatırlar", "victims": "kurbanlar" },
    questions: [ {q:"Was the plane flying to New York?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the bomb hidden inside a radio?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the plane fall onto a large city?", a_en:"No", a_tr:"Hayır"}, {q:"Did everyone on the plane die?", a_en:"Yes", a_tr:"Evet"}, {q:"Did parts of the plane hit houses?", a_en:"Yes", a_tr:"Evet"}, {q:"Did men from Libya plan the attack?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it the worst terrorist attack in the UK?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_TheLondonBombings.mp3"] = [{
    text: "The London bombings happened on July 7, 2005. People call it '7/7.' It was a busy morning in London. People were going to work. Four men carried backpacks with bombs. Three of them got on underground trains. They exploded their bombs at almost the same time. The trains were in tunnels, so it was very dark and scary. Later, the fourth man exploded his bomb on a red double-decker bus. The attacks killed 52 people and hurt hundreds more. The men who did this were from Britain, but they had extreme ideas. The attack stopped the whole city. People were unable to travel. It was a very frightening day for London. It changed how people feel about safety on trains and buses.",
    dict: { "busy": "yoğun/kalabalık", "morning": "sabah", "going": "gidiyorlardı", "work": "iş", "carried": "taşıdılar", "backpacks": "sırt çantaları", "underground": "yeraltı", "trains": "trenler", "almost": "neredeyse", "same": "aynı", "time": "zaman", "tunnels": "tüneller", "dark": "karanlık", "scary": "korkutucu", "later": "daha sonra", "fourth": "dördüncü", "red": "kırmızı", "bus": "otobüs", "hurt": "yaraladı", "hundreds": "yüzlerce", "extreme": "aşırı", "ideas": "fikirler", "stopped": "durdurdu", "whole": "bütün", "city": "şehir", "unable": "yapamayan/aciz", "travel": "seyahat etmek", "frightening": "korkutucu", "changed": "değiştirdi", "feel": "hissetmek", "about": "hakkında", "safety": "güvenlik" },
    questions: [ {q:"Did the bombings happen in the morning?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the men carry bombs in backpacks?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the trains in dark tunnels?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fourth man bomb a train too?", a_en:"No", a_tr:"Hayır"}, {q:"Did the attack stop the whole city?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the attackers from Britain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it change how people feel about safety?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_TheMadridBombings.mp3"] = [{
    text: "The Madrid train bombings happened in Spain in 2004. It was the morning rush hour. Many people were on trains going to work or school. Terrorists put backpacks with bombs on four different trains. Ten bombs exploded. It caused huge damage. The trains were destroyed. In this attack, 193 people died and almost 2,000 were hurt. It was the worst attack in the history of Spain. At first, the government thought a local group did it. But later, they found out it was a group connected to Al-Qaeda. The attack happened just three days before a big election. The people were very angry and sad. Millions of people went into the streets to protest against terrorism. It was a very difficult time for Spain.",
    dict: { "train": "tren", "rush hour": "yoğun saat", "school": "okul", "different": "farklı", "ten": "on", "exploded": "patladı", "caused": "sebep oldu", "huge": "kocaman", "damage": "hasar", "destroyed": "yok edildi", "died": "öldü", "almost": "neredeyse", "history": "tarih", "thought": "düşündü", "local": "yerel", "found out": "öğrendiler", "connected": "bağlantılı", "just": "sadece", "before": "önce", "big": "büyük", "election": "seçim", "angry": "öfkeli", "sad": "üzgün", "millions": "milyonlarca", "went": "gittiler", "streets": "sokaklar", "protest": "protesto etmek", "against": "karşı", "terrorism": "terörizm", "difficult": "zor", "time": "zaman" },
    questions: [ {q:"Did the bombings happen during morning rush hour?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the bombs on four different trains?", a_en:"Yes", a_tr:"Evet"}, {q:"Did ten bombs explode?", a_en:"Yes", a_tr:"Evet"}, {q:"Was this the worst attack in Spain's history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a local group do the attack?", a_en:"No", a_tr:"Hayır"}, {q:"Did it happen three days before an election?", a_en:"Yes", a_tr:"Evet"}, {q:"Did millions of people protest?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_TheMoscowTheaterSiege.mp3"] = [{
    text: "The Moscow Theater siege happened in Russia in 2002. A popular musical show was playing in a theater. Suddenly, about 40 rebels with guns came in. They stopped the show. They took 850 people as hostages. The rebels were from Chechnya. They wanted the Russian army to leave their land. They put explosives around the theater. They said they would blow it up. The siege lasted for three days. The Russian special forces wanted to save the people without fighting inside. They pumped a gas into the theater to make everyone fall asleep. Then the soldiers went in and killed the rebels. But the gas was too strong. It killed 132 of the hostages because they were unable to breathe. It was a tragedy because the rescue plan caused so many deaths.",
    dict: { "theater": "tiyatro", "popular": "popüler", "musical": "müzikal", "show": "gösteri", "suddenly": "aniden", "guns": "silahlar", "came in": "içeri girdiler", "stopped": "durdurdu", "took": "aldılar", "hostages": "rehineler", "wanted": "istediler", "leave": "terk etmek", "land": "toprak", "explosives": "patlayıcılar", "around": "etrafına", "blow up": "havaya uçurmak", "lasted": "sürdü", "special": "özel", "forces": "kuvvetler", "without": "olmadan", "pumped": "pompaladılar", "gas": "gaz", "make": "yapmak", "fall asleep": "uykuya dalmak", "went in": "içeri girdiler", "killed": "öldürdüler", "strong": "güçlü", "unable": "yapamayan", "breathe": "nefes almak", "tragedy": "trajedi", "rescue": "kurtarma", "plan": "plan", "caused": "sebep oldu", "deaths": "ölümler" },
    questions: [ {q:"Did rebels stop a musical show?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they take 850 people as hostages?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rebels want money?", a_en:"No", a_tr:"Hayır"}, {q:"Did the siege last for three days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the soldiers pump gas into the theater?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the gas make people fall asleep?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the gas kill 132 hostages?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_TheMumbaiAttacks.mp3"] = [{
    text: "The Mumbai attacks happened in India in 2008. It lasted for four days. Ten terrorists came to the city of Mumbai by boat. They had guns and grenades. They attacked many places in the city. They attacked a train station, a hospital, and a café. They also took over two very expensive hotels. One was the famous Taj Mahal Palace hotel. They took people as hostages inside the hotels. The police and soldiers fought them for a long time. The whole world watched it on TV. The hotels caught fire. In the end, 166 people died. Only one terrorist was caught alive. He was later punished by the court. People call this event 'India's 9/11' because it was so big and shocking.",
    dict: { "lasted": "sürdü", "days": "günler", "came": "geldiler", "boat": "tekne", "grenades": "el bombaları", "attacked": "saldırdılar", "places": "yerler", "train station": "tren istasyonu", "hospital": "hastane", "cafe": "kafe", "took over": "ele geçirdiler", "expensive": "pahalı", "hotels": "oteller", "famous": "ünlü", "inside": "içinde", "police": "polis", "soldiers": "askerler", "fought": "savaştılar", "long time": "uzun zaman", "whole": "bütün", "watched": "izledi", "caught fire": "alev aldı", "end": "son", "only": "sadece", "caught": "yakalandı", "alive": "canlı", "later": "daha sonra", "punished": "cezalandırıldı", "court": "mahkeme", "event": "olay", "shocking": "şok edici" },
    questions: [ {q:"Did the Mumbai attacks last for four days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the terrorists come by airplane?", a_en:"No", a_tr:"Hayır"}, {q:"Did they attack a hospital?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they take over the Taj Mahal Palace hotel?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hotels catch fire?", a_en:"Yes", a_tr:"Evet"}, {q:"Was only one terrorist caught alive?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people call it India's 9/11?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_TheMunichMassacre.mp3"] = [{
    text: "The Munich Olympics massacre happened in Germany in 1972. The Olympic Games are a time for peace and sports. But a group of terrorists called 'Black September' broke into the place where athletes slept. They went to the rooms of the Israeli team. They killed two athletes and took nine others as prisoners. They wanted Israel to release people from jail. The German police tried to trick the terrorists and save the athletes at an airport. But the plan failed. There was a gunfight. The terrorists killed all nine hostages. A police officer also died. The Olympic Games were stopped for a day. It was very sad. After this, security at sports events became much stricter to protect the players.",
    dict: { "massacre": "katliam", "peace": "barış", "sports": "spor", "called": "adlandırılan", "broke into": "zorla girdiler", "place": "yer", "athletes": "sporcular", "slept": "uyudular", "rooms": "odalar", "team": "takım", "killed": "öldürdüler", "two": "iki", "nine": "dokuz", "prisoners": "mahkumlar/esirler", "release": "serbest bırakmak", "jail": "hapishane", "police": "polis", "tried": "denedi", "trick": "kandırmak", "save": "kurtarmak", "airport": "havalimanı", "plan": "plan", "failed": "başarısız oldu", "gunfight": "silahlı çatışma", "officer": "memur", "stopped": "durduruldu", "day": "gün", "security": "güvenlik", "events": "etkinlikler", "stricter": "daha katı", "protect": "korumak", "players": "oyuncular" },
    questions: [ {q:"Did the massacre happen during the Olympic Games?", a_en:"Yes", a_tr:"Evet"}, {q:"Did terrorists break into the athletes' rooms?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they take nine athletes as prisoners?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the terrorists want money?", a_en:"No", a_tr:"Hayır"}, {q:"Did the police plan at the airport fail?", a_en:"Yes", a_tr:"Evet"}, {q:"Did all nine hostages die?", a_en:"Yes", a_tr:"Evet"}, {q:"Did security become stricter after this?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_TheNairobiBombing.mp3"] = [{
    text: "The Nairobi Embassy bombing happened in 1998. Terrorists attacked the United States embassies in two countries in Africa: Kenya and Tanzania. They used trucks filled with bombs. The bombs exploded at almost the same time in both cities. The attack in Nairobi, Kenya, was very bad. The embassy was damaged, but a building next to it fell down completely. This building was full of offices and a school. More than 200 people died. Most of them were people from Kenya. Thousands were hurt by flying glass and debris. This attack was planned by Osama bin Laden. It was the first time many people heard of his group, Al-Qaeda. It showed that terrorism was a global problem.",
    dict: { "embassy": "büyükelçilik", "attacked": "saldırdılar", "countries": "ülkeler", "used": "kullandılar", "trucks": "kamyonlar", "filled": "dolu", "exploded": "patladı", "almost": "neredeyse", "same": "aynı", "cities": "şehirler", "bad": "kötü", "damaged": "hasarlı", "next to": "yanında", "completely": "tamamen", "full": "dolu", "offices": "ofisler", "school": "okul", "died": "öldü", "thousands": "binlerce", "hurt": "yaralandı", "flying": "uçan", "glass": "cam", "debris": "enkaz", "planned": "planlandı", "first time": "ilk kez", "heard": "duydular", "group": "grup", "showed": "gösterdi", "global": "küresel", "problem": "sorun" },
    questions: [ {q:"Did terrorists attack US embassies?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use trucks filled with bombs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bombs explode at the same time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a building next to the embassy fall down?", a_en:"Yes", a_tr:"Evet"}, {q:"Were most of the victims from the United States?", a_en:"No", a_tr:"Hayır"}, {q:"Were thousands hurt by flying glass?", a_en:"Yes", a_tr:"Evet"}, {q:"Was this attack planned by Osama bin Laden?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_TheNorwayAttacks.mp3"] = [{
    text: "The Norway attacks happened in 2011. A man named Anders Behring Breivik did it alone. He had extreme political ideas. First, he put a bomb in a car near government buildings in the city of Oslo. The explosion killed eight people. Then, he went to a small island called Utøya. There was a summer camp for teenagers there. He dressed like a police officer. He called the young people to him and then started shooting. He killed 69 people on the island. In total, 77 people died that day. It was a huge shock because Norway is usually a very safe and peaceful country. The man was arrested and put in prison. The people of Norway came together to show love and support for the victims.",
    dict: { "alone": "yalnız", "extreme": "aşırı", "political": "siyasi", "ideas": "fikirler", "put": "koydu", "car": "araba", "near": "yakın", "government": "hükümet", "buildings": "binalar", "explosion": "patlama", "killed": "öldürdü", "went": "gitti", "small": "küçük", "island": "ada", "summer": "yaz", "camp": "kamp", "teenagers": "gençler", "dressed": "giyindi", "like": "gibi", "officer": "memur", "called": "çağırdı", "young": "genç", "started": "başladı", "shooting": "ateş etmeye", "total": "toplam", "huge": "kocaman", "shock": "şok", "usually": "genellikle", "safe": "güvenli", "peaceful": "huzurlu", "arrested": "tutuklandı", "prison": "hapishane", "together": "birlikte", "show": "göstermek", "love": "sevgi", "support": "destek" },
    questions: [ {q:"Did the attacker act alone?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he put a bomb in a car in Oslo?", a_en:"Yes", a_tr:"Evet"}, {q:"Was there a summer camp on the island?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he dress like a doctor?", a_en:"No", a_tr:"Hayır"}, {q:"Did 69 people die on the island?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Norway usually a safe country?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the man put in prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_TheOklahomaCityBombing.mp3"] = [{
    text: "The Oklahoma City bombing happened in the USA in 1995. A man named Timothy McVeigh was angry at the government. He rented a truck and filled it with explosives. He parked it in front of a big government building. The bomb exploded and destroyed the front of the building. It was a huge explosion. It killed 168 people. Sadly, there was a daycare center for children in the building. Nineteen small children died. More than 600 people were hurt. McVeigh was caught by a police officer soon after. He was put on trial and executed. Before 9/11, this was the worst terrorist attack in America. It made people realize that terrorism can come from inside their own country.",
    dict: { "angry": "öfkeli", "government": "hükümet", "rented": "kiraladı", "truck": "kamyon", "filled": "doldurdu", "explosives": "patlayıcılar", "parked": "park etti", "front": "önünde", "building": "bina", "exploded": "patladı", "destroyed": "yok etti", "huge": "kocaman", "explosion": "patlama", "killed": "öldürdü", "sadly": "ne yazık ki", "daycare": "kreş", "children": "çocuklar", "small": "küçük", "hurt": "yaralandı", "caught": "yakalandı", "police": "polis", "officer": "memur", "soon": "kısa süre", "after": "sonra", "trial": "duruşma", "executed": "idam edildi", "before": "önce", "worst": "en kötü", "realize": "fark etmek", "inside": "içinden", "own": "kendi", "country": "ülke" },
    questions: [ {q:"Was the attacker angry at the government?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he park a truck in front of the building?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bomb destroy the front of the building?", a_en:"Yes", a_tr:"Evet"}, {q:"Was there a daycare center in the building?", a_en:"Yes", a_tr:"Evet"}, {q:"Did 19 small children survive?", a_en:"No", a_tr:"Hayır"}, {q:"Was the attacker caught by a police officer?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he executed?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_TheParisAttacks.mp3"] = [{
    text: "The Paris attacks happened in France in November 2015. It was a Friday night. Terrorists attacked many places in the city at the same time. Some blew themselves up outside a soccer stadium. Others shot people in restaurants and cafes. The worst attack was at a concert hall called the Bataclan. A rock band was playing music. The terrorists went inside and shot into the crowd. They took people as hostages. The police had to break in to stop them. In one night, 130 people were killed. Most of them died at the concert hall. The group ISIS said they did it. France was in shock. The government closed the borders and declared a state of emergency. People around the world put French flags on their profiles to show support.",
    dict: { "Friday": "Cuma", "night": "gece", "attacked": "saldırdılar", "places": "yerler", "same": "aynı", "time": "zaman", "blew up": "havaya uçurdular", "themselves": "kendilerini", "outside": "dışında", "soccer": "futbol", "stadium": "stadyum", "shot": "vurdular/ateş ettiler", "restaurants": "restoranlar", "cafes": "kafeler", "worst": "en kötü", "concert": "konser", "hall": "salon", "band": "grup (müzik)", "playing": "çalıyordu", "inside": "içeri", "crowd": "kalabalık", "took": "aldılar", "hostages": "rehineler", "police": "polis", "break in": "zorla girmek", "stop": "durdurmak", "killed": "öldürüldü", "died": "öldüler", "shock": "şok", "government": "hükümet", "closed": "kapattı", "borders": "sınırlar", "declared": "ilan etti", "state of emergency": "olağanüstü hal", "world": "dünya", "flags": "bayraklar", "profiles": "profiller", "show": "göstermek", "support": "destek" },
    questions: [ {q:"Did the attacks happen on a Friday night?", a_en:"Yes", a_tr:"Evet"}, {q:"Did terrorists attack a soccer stadium?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they shoot people in restaurants?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the worst attack at a school?", a_en:"No", a_tr:"Hayır"}, {q:"Did the police break in to stop them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government close the borders?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people put French flags on their profiles?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_ThePeshawarSchoolMassacre.mp3"] = [{
    text: "The Peshawar school massacre happened in Pakistan in 2014. It was a horrific day. Seven gunmen attacked a school run by the army. The school was for children. The gunmen went into the school and started shooting everyone. They asked for no money or demands. They just wanted to kill. The teachers tried to protect the students. The attack lasted for hours. The army soldiers came and killed the gunmen. But 149 people were already dead. Most of them were children. It was very cruel. The whole country cried for the children. After this, Pakistan decided to fight harder against terrorists. They made new laws to punish them. It is remembered as the saddest day in Pakistan's history.",
    dict: { "massacre": "katliam", "horrific": "korkunç", "gunmen": "silahlı adamlar", "attacked": "saldırdılar", "school": "okul", "run by": "tarafından yönetilen", "army": "ordu", "children": "çocuklar", "went": "gittiler", "started": "başladılar", "shooting": "ateş etmeye", "everyone": "herkes", "ask": "istemek/sormak", "money": "para", "demands": "talepler", "just": "sadece", "wanted": "istediler", "kill": "öldürmek", "teachers": "öğretmenler", "tried": "denediler", "protect": "korumak", "students": "öğrenciler", "lasted": "sürdü", "hours": "saatler", "soldiers": "askerler", "came": "geldiler", "already": "zaten", "dead": "ölü", "cruel": "zalim", "whole": "bütün", "country": "ülke", "cried": "ağladı", "decided": "karar verdi", "fight": "savaşmak", "harder": "daha sert", "against": "karşı", "made": "yaptı", "new": "yeni", "laws": "yasalar", "punish": "cezalandırmak", "remembered": "hatırlanır", "saddest": "en üzücü", "history": "tarih" },
    questions: [ {q:"Was the school run by the army?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the gunmen ask for money?", a_en:"No", a_tr:"Hayır"}, {q:"Did the teachers try to protect the students?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the attack last for hours?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the army soldiers kill the gunmen?", a_en:"Yes", a_tr:"Evet"}, {q:"Were most of the victims children?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Pakistan make new laws to punish terrorists?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_TheTokyoSubwayAttack.mp3"] = [{
    text: "The Tokyo subway attack happened in Japan in 1995. It was done by a cult group. They wanted to start a war. Five members of the group got on subway trains in the morning. It was rush hour, so the trains were full. They carried bags with liquid poison called sarin. They poked holes in the bags and left the trains. The liquid turned into gas. The gas made people very sick. They were unable to breathe or see well. The gas spread through the stations. It killed 13 people and made thousands of people sick. It was very scary because nobody could see the gas. It was the first time terrorists used chemical weapons in a city. Japan arrested the leader of the cult and punished him.",
    dict: { "subway": "metro", "attack": "saldırı", "done": "yapıldı", "cult": "tarikat", "group": "grup", "wanted": "istediler", "start": "başlatmak", "war": "savaş", "members": "üyeler", "got on": "bindiler", "trains": "trenler", "morning": "sabah", "rush hour": "yoğun saat", "full": "dolu", "carried": "taşıdılar", "bags": "çantalar", "liquid": "sıvı", "poison": "zehir", "called": "adlandırılan", "poked": "deldi", "holes": "delikler", "left": "ayrıldılar", "turned into": "dönüştü", "gas": "gaz", "sick": "hasta", "unable": "yapamayan", "breathe": "nefes almak", "see": "görmek", "well": "iyi", "spread": "yayıldı", "stations": "istasyonlar", "killed": "öldürdü", "thousands": "binlerce", "scary": "korkutucu", "nobody": "hiç kimse", "first time": "ilk kez", "used": "kullandılar", "chemical": "kimyasal", "weapons": "silahlar", "city": "şehir", "arrested": "tutukladı", "leader": "lider", "punished": "cezalandırdı" },
    questions: [ {q:"Was the attack done by a cult group?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they get on trains during rush hour?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they carry solid poison?", a_en:"No", a_tr:"Hayır"}, {q:"Did the liquid turn into gas?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the people see the gas?", a_en:"No", a_tr:"Hayır"}, {q:"Did the gas make thousands of people sick?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Japan arrest the leader of the cult?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_TheWestgateMallSiege.mp3"] = [{
    text: "The Westgate Mall siege happened in Kenya in 2013. The Westgate Mall was a very nice shopping center. Rich people and foreigners went there to shop. Four men with guns entered the mall. They were from a group called Al-Shabaab. They threw grenades and shot at shoppers. They stayed in the mall for four days. The police and army surrounded the building. It was difficult to catch the men because the mall was big. There was a fire, and part of the building fell down. In the end, 67 people died. Many others were hurt. The terrorists said they attacked because Kenya sent soldiers to Somalia. It made people in Kenya very afraid to go to public places for a while.",
    dict: { "siege": "kuşatma", "nice": "güzel", "shopping": "alışveriş", "center": "merkez", "rich": "zengin", "foreigners": "yabancılar", "shop": "alışveriş yapmak", "men": "adamlar", "guns": "silahlar", "entered": "girdiler", "mall": "alışveriş merkezi", "called": "adlandırılan", "threw": "attılar", "grenades": "el bombaları", "shot": "ateş ettiler", "shoppers": "müşteriler", "stayed": "kaldılar", "days": "günler", "police": "polis", "army": "ordu", "surrounded": "kuşattı", "building": "bina", "difficult": "zor", "catch": "yakalamak", "big": "büyük", "fire": "yangın", "part": "parça", "fell down": "yıkıldı/düştü", "end": "son", "died": "öldü", "others": "diğerleri", "hurt": "yaralandı", "said": "söyledi", "attacked": "saldırdılar", "because": "çünkü", "sent": "gönderdi", "soldiers": "askerler", "afraid": "korkmuş", "public": "halka açık", "places": "yerler", "while": "bir süre" },
    questions: [ {q:"Was the Westgate Mall a shopping center?", a_en:"Yes", a_tr:"Evet"}, {q:"Did four men with guns enter the mall?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they throw grenades?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they stay in the mall for four days?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it easy to catch the men?", a_en:"No", a_tr:"Hayır"}, {q:"Did part of the building fall down?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Kenya send soldiers to Somalia?", a_en:"Yes", a_tr:"Evet"} ]
}];
